# Generated by Django 5.2.6 on 2025-09-24 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Procedimentos_Cirurgicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('especialidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='upme.especialidade')),
            ],
        ),
        migrations.CreateModel(
            name='Kit_Procedimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='upme.kit')),
                ('procedimento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='upme.procedimentos_cirurgicos')),
            ],
        ),
        migrations.CreateModel(
            name='Kit_Procedimento_Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='upme.kit_procedimentos')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='upme.material')),
            ],
        ),
    ]
