# Generated by Django 5.2.6 on 2025-09-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit_procedimento_material',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
