# Generated by Django 5.2.6 on 2025-09-24 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upme', '0002_kit_procedimento_material_quantidade'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kit_Procedimento_Material',
            new_name='Kit_Material',
        ),
        migrations.RenameModel(
            old_name='Kit_Procedimentos',
            new_name='Kit_Procedimento',
        ),
        migrations.RenameModel(
            old_name='Procedimentos_Cirurgicos',
            new_name='Procedimento',
        ),
        migrations.AlterField(
            model_name='kit_material',
            name='kit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='upme.kit'),
        ),
    ]
