# Generated by Django 5.2.6 on 2025-09-25 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upme', '0003_rename_kit_procedimento_material_kit_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimento',
            name='especialidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='upme.especialidade'),
        ),
        migrations.DeleteModel(
            name='Kit_Procedimento',
        ),
    ]
