# Generated by Django 5.2.6 on 2025-09-26 19:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upme', '0004_procedimento_especialidade_delete_kit_procedimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('prontuario', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cirurgia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico', models.CharField(blank=True, max_length=200, null=True)),
                ('sala', models.CharField(blank=True, max_length=50, null=True)),
                ('data', models.DateField(default=datetime.date.today)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upme.procedimento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upme.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='CirurgiaKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cirurgia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upme.cirurgia')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upme.kit')),
            ],
        ),
        migrations.CreateModel(
            name='CirurgiaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_solicitada', models.IntegerField(default=1)),
                ('quantidade_fornecida', models.IntegerField(default=0)),
                ('quantidade_devolvida', models.IntegerField(default=0)),
                ('cirurgia_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upme.cirurgiakit')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upme.material')),
            ],
        ),
    ]
