# Generated by Django 5.2.6 on 2025-10-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upme', '0005_paciente_cirurgia_cirurgiakit_cirurgiamaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cirurgia',
            name='procedimento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
