# Generated by Django 5.2.6 on 2025-10-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upme', '0006_alter_cirurgia_procedimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cirurgia',
            name='especialidade',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
