# Generated by Django 5.2.6 on 2025-10-06 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upme', '0007_cirurgia_especialidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cirurgiamaterial',
            name='cirurgia_kit',
        ),
        migrations.AddField(
            model_name='cirurgiamaterial',
            name='cirurgia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='upme.cirurgia'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CirurgiaKit',
        ),
    ]
