# Generated by Django 5.2.6 on 2025-10-07 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upme', '0008_remove_cirurgiamaterial_cirurgia_kit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cirurgiamaterial',
            name='cirurgia',
        ),
        migrations.AlterField(
            model_name='cirurgiamaterial',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='upme.material'),
        ),
        migrations.CreateModel(
            name='CirurgiaKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cirurgia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upme.cirurgia')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upme.kit')),
            ],
        ),
        migrations.AddField(
            model_name='cirurgiamaterial',
            name='cirurgia_kit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='upme.cirurgiakit'),
        ),
    ]
