# Generated by Django 5.2.6 on 2025-10-07 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upme', '0009_remove_cirurgiamaterial_cirurgia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cirurgiamaterial',
            name='cirurgia_kit',
        ),
        migrations.AddField(
            model_name='cirurgiamaterial',
            name='cirurgia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='upme.cirurgia'),
        ),
        migrations.DeleteModel(
            name='CirurgiaKit',
        ),
    ]
