# Generated by Django 5.2.6 on 2025-10-07 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upme', '0010_remove_cirurgiamaterial_cirurgia_kit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cirurgiamaterial',
            name='kit_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='upme.kit_material'),
        ),
    ]
