# Generated by Django 5.2.7 on 2026-01-30 12:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=60, unique=True, verbose_name='Identificador da caixa')),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('data_cadastro', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name='Referência')),
                ('fabricante', models.CharField(blank=True, max_length=100)),
                ('unidade', models.CharField(default='un', max_length=20, verbose_name='Unidade')),
            ],
        ),
        migrations.CreateModel(
            name='CaixaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_esperada', models.PositiveIntegerField(default=1, verbose_name='Qtde esperada')),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_padrao', to='opme.caixa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='opme.produto')),
            ],
            options={
                'verbose_name': 'Item padrão da caixa',
                'verbose_name_plural': 'Itens padrão da caixa',
                'ordering': ['produto__descricao'],
                'unique_together': {('caixa', 'produto')},
            },
        ),
        migrations.CreateModel(
            name='Consignacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consignacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da consignação / recebimento no hospital')),
                ('data_devolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data efetiva da devolução')),
                ('status', models.CharField(choices=[('CONSIGNADO', 'Consignado (em uso no hospital)'), ('DEVOLVIDO', 'Devolvido (total)'), ('DEVOLVIDO_PARCIAL', 'Devolvido parcial')], default='CONSIGNADO', max_length=20, verbose_name='Status da consignação')),
                ('observacao', models.TextField(blank=True, verbose_name='Observações gerais da consignação')),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='opme.caixa', verbose_name='Caixa / Kit')),
                ('responsavel_devolucao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consignacoes_devolvidas', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pela devolução / conferência')),
                ('responsavel_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consignacoes_entregues', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pela entrega / consignação')),
            ],
            options={
                'verbose_name': 'Consignação OPME',
                'verbose_name_plural': 'Consignações OPME',
                'ordering': ['-data_consignacao'],
            },
        ),
        migrations.CreateModel(
            name='ConsignacaoFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CHEGADA', 'Foto de Chegada / Recebimento'), ('DEVOLUCAO', 'Foto de Devolução')], max_length=10, verbose_name='Etapa')),
                ('imagem', models.ImageField(upload_to='consignacoes/fotos/%Y/%m/%d/', verbose_name='Imagem')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descrição / Observação')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('consignacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='opme.consignacao')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foto da Consignação',
                'verbose_name_plural': 'Fotos do Consignação',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='caixa',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='opme.empresa'),
        ),
        migrations.CreateModel(
            name='ConsignacaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_recebida', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Qtde real recebida na entrega')),
                ('quantidade_devolvida', models.PositiveIntegerField(default=0, verbose_name='Qtde devolvida')),
                ('removido_na_chegada', models.BooleanField(default=False, verbose_name='Removido/negado na conferência de chegada')),
                ('observacao', models.TextField(blank=True)),
                ('caixa_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='opme.caixaitem')),
                ('consignacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='opme.consignacao')),
            ],
            options={
                'verbose_name': 'Item da consignação',
                'verbose_name_plural': 'Itens da consignação',
                'unique_together': {('consignacao', 'caixa_item')},
            },
        ),
    ]
