# Generated by Django 5.2.7 on 2026-02-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignacao',
            name='observacao_devolucao',
            field=models.TextField(blank=True, verbose_name='Observações gerais da devolução'),
        ),
        migrations.AddField(
            model_name='consignacaoitem',
            name='observacao_devolucao',
            field=models.TextField(blank=True),
        ),
    ]
