# Generated by Django 5.2.7 on 2026-03-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opme', '0002_consignacao_observacao_devolucao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='identificador',
            field=models.CharField(max_length=200, unique=True, verbose_name='Identificador da caixa'),
        ),
    ]
