# Generated by Django 5.2.7 on 2026-05-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opme', '0003_alter_caixa_identificador'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignacaoitem',
            name='quantidade_reposta',
            field=models.PositiveIntegerField(default=0, verbose_name='Qtde reposta'),
        ),
    ]
