# Generated by Django 5.2.7 on 2026-05-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opme', '0004_consignacaoitem_quantidade_reposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignacaoitem',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consignacaoitem',
            name='observacao_devolucao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
