# Generated by Django 5.2.7 on 2026-05-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opme', '0005_alter_consignacaoitem_observacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignacao',
            name='observacao_devolucao',
            field=models.TextField(blank=True, null=True, verbose_name='Observações gerais da devolução'),
        ),
    ]
