# Generated by Django 5.2.6 on 2025-12-02 15:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('prontuario', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GiroSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataInicioCirurgia', models.DateField(null=True)),
                ('dataFinalCirurgia', models.DateField(null=True)),
                ('dataSaidaSala', models.DateField(null=True)),
                ('dataDesmontagemSala', models.DateField(null=True)),
                ('dataInicioLimpeza', models.DateField(null=True)),
                ('dataFinalLimpeza', models.DateField(null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centrocirurgico.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Cirurgia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.CharField(blank=True, max_length=200, null=True)),
                ('procedimento', models.CharField(blank=True, max_length=200, null=True)),
                ('medico', models.CharField(blank=True, max_length=200, null=True)),
                ('sala', models.CharField(blank=True, max_length=50, null=True)),
                ('data', models.DateField(default=datetime.date.today)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centrocirurgico.paciente')),
            ],
        ),
    ]
