# Generated by Django 5.2.6 on 2025-12-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centrocirurgico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='girosala',
            name='dataDesmontagemSala',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='girosala',
            name='dataFinalCirurgia',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='girosala',
            name='dataFinalLimpeza',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='girosala',
            name='dataInicioCirurgia',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='girosala',
            name='dataInicioLimpeza',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='girosala',
            name='dataSaidaSala',
            field=models.DateTimeField(null=True),
        ),
    ]
