# Generated by Django 5.2.6 on 2025-12-02 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centrocirurgico', '0002_alter_girosala_datadesmontagemsala_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='girosala',
            name='cirurgia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='centrocirurgico.cirurgia'),
            preserve_default=False,
        ),
    ]
