# Generated by Django 5.2.6 on 2025-12-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centrocirurgico', '0003_girosala_cirurgia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='girosala',
            old_name='dataDesmontagemSala',
            new_name='dataFinalDesmontagemSala',
        ),
        migrations.AddField(
            model_name='girosala',
            name='dataInicioDesmontagemSala',
            field=models.DateTimeField(null=True),
        ),
    ]
