# Generated by Django 5.2.7 on 2025-12-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centrocirurgico', '0004_rename_datadesmontagemsala_girosala_datafinaldesmontagemsala_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='girosala',
            name='dataSalaLiberada',
            field=models.DateTimeField(null=True),
        ),
    ]
