# Generated by Django 5.2.7 on 2026-05-14 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centrocirurgico', '0005_girosala_datasalaliberada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LimpezaTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da limpeza')),
                ('centro_cirurgico', models.CharField(choices=[('CCA', 'Centro Cirúrgico Adulto'), ('CCI', 'Centro Cirúrgico Infantil'), ('CCOF', 'Centro Cirúrgico Oftalmológico')], max_length=10, verbose_name='Centro Cirúrgico')),
                ('sala', models.CharField(max_length=10, verbose_name='Sala')),
                ('data_hora_enfermagem', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Enfermagem')),
                ('data_hora_higienizacao', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Higienização')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limpezas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('usuario_enfermagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limpezas_enfermagem', to=settings.AUTH_USER_MODEL, verbose_name='Responsável Enfermagem')),
                ('usuario_higienizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limpezas_higienizacao', to=settings.AUTH_USER_MODEL, verbose_name='Responsável Higienização')),
            ],
            options={
                'verbose_name': 'Limpeza Terminal',
                'verbose_name_plural': 'Limpezas Terminais',
                'ordering': ['-data', '-criado_em'],
                'unique_together': {('data', 'centro_cirurgico', 'sala')},
            },
        ),
    ]
