# Generated by Django 5.2.7 on 2026-05-19 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centrocirurgico', '0006_limpezaterminal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limpezaterminal',
            name='data_hora_enfermagem',
        ),
        migrations.RemoveField(
            model_name='limpezaterminal',
            name='data_hora_higienizacao',
        ),
        migrations.RemoveField(
            model_name='limpezaterminal',
            name='usuario_enfermagem',
        ),
        migrations.RemoveField(
            model_name='limpezaterminal',
            name='usuario_higienizacao',
        ),
        migrations.AddField(
            model_name='limpezaterminal',
            name='fim_enfermagem',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim Enfermagem'),
        ),
        migrations.AddField(
            model_name='limpezaterminal',
            name='fim_higienizacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim Higienização'),
        ),
        migrations.AddField(
            model_name='limpezaterminal',
            name='inicio_enfermagem',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Início Enfermagem'),
        ),
        migrations.AddField(
            model_name='limpezaterminal',
            name='inicio_higienizacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Início Higienização'),
        ),
        migrations.AddField(
            model_name='limpezaterminal',
            name='usuario_fim_enfermagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fim_limpezas_enfermagem', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='limpezaterminal',
            name='usuario_fim_higienizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fim_limpezas_higienizacao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='limpezaterminal',
            name='usuario_inicio_enfermagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inicio_limpezas_enfermagem', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='limpezaterminal',
            name='usuario_inicio_higienizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inicio_limpezas_higienizacao', to=settings.AUTH_USER_MODEL),
        ),
    ]
