# Generated by Django 5.2.7 on 2026-06-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centrocirurgico', '0007_remove_limpezaterminal_data_hora_enfermagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='girosala',
            name='observacao',
            field=models.TextField(default='', null=True),
        ),
    ]
