# Generated by Django 5.2.6 on 2026-08-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centrocirurgico', '0008_girosala_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='girosala',
            name='tipolavagem',
            field=models.CharField(blank=True, default='C', max_length=1, null=True),
        ),
    ]
