# Generated by Django 5.2.6 on 2026-08-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centrocirurgico', '0009_girosala_tipolavagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='girosala',
            name='tipolavagem',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
