# Generated by Django 5.2.6 on 2026-08-14 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centrocirurgico', '0010_alter_girosala_tipolavagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='girosala',
            old_name='tipolavagem',
            new_name='tipoLimpeza',
        ),
    ]
