# Generated by Django 5.2.7 on 2026-03-13 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BolsaSangue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bolsa', models.CharField(max_length=50, unique=True)),
                ('hemocomponente', models.CharField(max_length=50)),
                ('grupo_sanguineo', models.CharField(max_length=3)),
                ('fator_rh', models.CharField(max_length=1)),
                ('data_coleta', models.DateField()),
                ('data_validade', models.DateField()),
                ('status', models.CharField(choices=[('estoque', 'Em estoque'), ('reservada', 'Reservada'), ('liberada', 'Liberada'), ('transfundida', 'Transfundida'), ('descartada', 'Descartada')], default='estoque', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('prontuario', models.CharField(max_length=50)),
                ('grupo_sanguineo', models.CharField(max_length=3)),
                ('fator_rh', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='RecebimentoHemocomponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_recebimento', models.DateTimeField(auto_now_add=True)),
                ('recebido_por', models.CharField(max_length=200)),
                ('observacoes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoHemocomponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('hemocomponente', models.CharField(max_length=50)),
                ('grupo_sanguineo', models.CharField(blank=True, max_length=3, null=True)),
                ('fator_rh', models.CharField(blank=True, max_length=1, null=True)),
                ('quantidade', models.IntegerField()),
                ('justificativa', models.TextField()),
                ('solicitante', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('solicitado', 'Solicitado'), ('atendido', 'Atendido'), ('parcial', 'Atendido Parcialmente'), ('cancelado', 'Cancelado')], default='solicitado', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProvaCruzada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_prova', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.CharField(choices=[('compativel', 'Compatível'), ('incompativel', 'Incompatível')], max_length=20)),
                ('realizado_por', models.CharField(max_length=200)),
                ('observacoes', models.TextField(blank=True)),
                ('bolsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uhh.bolsasangue')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uhh.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='LiberacaoBolsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_liberacao', models.DateTimeField(auto_now_add=True)),
                ('liberado_por', models.CharField(max_length=200)),
                ('setor_destino', models.CharField(max_length=200)),
                ('observacoes', models.TextField(blank=True)),
                ('prova_cruzada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uhh.provacruzada')),
            ],
        ),
        migrations.AddField(
            model_name='bolsasangue',
            name='recebimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uhh.recebimentohemocomponente'),
        ),
        migrations.AddField(
            model_name='recebimentohemocomponente',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uhh.solicitacaohemocomponente'),
        ),
    ]
