# Generated by Django 5.2.7 on 2026-03-13 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uhh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevolucaoBolsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_devolucao', models.DateTimeField(auto_now_add=True)),
                ('devolvido_por', models.CharField(max_length=200)),
                ('setor_origem', models.CharField(max_length=200)),
                ('condicao_bolsa', models.CharField(help_text='Ex: refrigerada, temperatura ambiente, violação de lacre', max_length=200)),
                ('status', models.CharField(choices=[('aprovada', 'Aprovada para Reintegração'), ('descartada', 'Descartada')], max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('bolsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uhh.bolsasangue')),
                ('liberacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uhh.liberacaobolsa')),
            ],
        ),
    ]
