# Generated by Django 5.2.7 on 2026-03-13 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uhh', '0002_devolucaobolsa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacaohemocomponente',
            name='fator_rh',
        ),
        migrations.RemoveField(
            model_name='solicitacaohemocomponente',
            name='grupo_sanguineo',
        ),
        migrations.RemoveField(
            model_name='solicitacaohemocomponente',
            name='hemocomponente',
        ),
        migrations.RemoveField(
            model_name='solicitacaohemocomponente',
            name='justificativa',
        ),
        migrations.RemoveField(
            model_name='solicitacaohemocomponente',
            name='quantidade',
        ),
        migrations.AlterField(
            model_name='solicitacaohemocomponente',
            name='status',
            field=models.CharField(default='aberta', max_length=20),
        ),
        migrations.CreateModel(
            name='ItemSolicitacaoHemocomponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hemocomponente', models.CharField(max_length=200)),
                ('grupo_sanguineo', models.CharField(max_length=3)),
                ('fator_rh', models.CharField(max_length=1)),
                ('quantidade', models.IntegerField()),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='uhh.solicitacaohemocomponente')),
            ],
        ),
        migrations.CreateModel(
            name='RetornoSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recebido', models.BooleanField(default=False)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True)),
                ('bolsa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uhh.bolsasangue')),
                ('item_solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uhh.itemsolicitacaohemocomponente')),
            ],
        ),
    ]
