# Generated by Django 5.2.7 on 2026-03-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uhh', '0003_remove_solicitacaohemocomponente_fator_rh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolsasangue',
            name='numero_macarrao',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
