# Generated by Django 5.2.7 on 2026-03-17 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uhh', '0004_bolsasangue_numero_macarrao'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolsasangue',
            name='data_criacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bolsasangue',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='itemsolicitacaohemocomponente',
            name='ml',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitacaohemocomponente',
            name='unidade',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bolsasangue',
            name='recebimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolsas', to='uhh.recebimentohemocomponente'),
        ),
        migrations.AlterField(
            model_name='bolsasangue',
            name='status',
            field=models.CharField(choices=[('estoque', 'Em estoque'), ('reservada', 'Reservada'), ('liberada', 'Liberada'), ('transfundida', 'Transfundida'), ('devolvida', 'Devolvida'), ('descartada', 'Descartada')], default='estoque', max_length=20),
        ),
        migrations.AlterField(
            model_name='devolucaobolsa',
            name='bolsa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devolucoes', to='uhh.bolsasangue'),
        ),
        migrations.AlterField(
            model_name='devolucaobolsa',
            name='liberacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devolucoes', to='uhh.liberacaobolsa'),
        ),
        migrations.AlterField(
            model_name='itemsolicitacaohemocomponente',
            name='fator_rh',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='itemsolicitacaohemocomponente',
            name='grupo_sanguineo',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='itemsolicitacaohemocomponente',
            name='hemocomponente',
            field=models.CharField(choices=[('CH', 'Concentrado de Hemácias'), ('CHFILTRADO', 'Concentrado de Hemácias Filtrado'), ('FRACAOCH', 'Fração de Concentrado de Hemácias'), ('PLASMA', 'Plasma Fresco Congelado'), ('PLAQUETAS', 'Concentrado de Plaquetas'), ('CRIO', 'Crioprecipitado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='itemsolicitacaohemocomponente',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='liberacaobolsa',
            name='prova_cruzada',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liberacao', to='uhh.provacruzada'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='prontuario',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='provacruzada',
            name='bolsa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provas', to='uhh.bolsasangue'),
        ),
        migrations.AlterField(
            model_name='provacruzada',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provas', to='uhh.paciente'),
        ),
        migrations.AlterField(
            model_name='recebimentohemocomponente',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recebimentos', to='uhh.solicitacaohemocomponente'),
        ),
        migrations.AlterField(
            model_name='retornosolicitacao',
            name='bolsa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uhh.bolsasangue'),
        ),
        migrations.AlterField(
            model_name='retornosolicitacao',
            name='item_solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retornos', to='uhh.itemsolicitacaohemocomponente'),
        ),
        migrations.AlterField(
            model_name='solicitacaohemocomponente',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('atendida_parcial', 'Atendida Parcialmente'), ('atendida_total', 'Atendida Totalmente'), ('cancelada', 'Cancelada')], default='aberta', max_length=20),
        ),
        migrations.AddIndex(
            model_name='bolsasangue',
            index=models.Index(fields=['status'], name='uhh_bolsasa_status_a01406_idx'),
        ),
        migrations.AddIndex(
            model_name='bolsasangue',
            index=models.Index(fields=['grupo_sanguineo', 'fator_rh'], name='uhh_bolsasa_grupo_s_69ca6f_idx'),
        ),
    ]
