# Generated by Django 5.2.7 on 2026-03-17 16:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uhh', '0005_bolsasangue_data_criacao_bolsasangue_observacoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolsasangue',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
