# Generated by Django 5.2.7 on 2026-03-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uhh', '0006_alter_bolsasangue_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolsasangue',
            name='volume_ml',
            field=models.PositiveIntegerField(default=0, help_text='Ex: 250, 300, 450', verbose_name='Volume (ml)'),
        ),
    ]
